---
- name: Check AIX OS Level
  hosts: aix-ssokt
  tasks:
    - name: Ping connection to AIX Server
      ansible.builtin.ping:

    - name: Get OS Level
      shell: "oslevel -s"
      register: output_oslevel

    - name: Print the oslevel
      debug:
        msg: "{{ ansible hostname }} has the AIX oslevel of {{ output_oslevel.stdout }}"